### PR TITLE
Use GitHub Actions instead of Travis CI (retry)

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Code from #38 adapted to verify how webrick is doing on jruby.

(Got here from https://github.com/rubygems/rubygems/issues/3451).

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Marking this as a draft since I'm just experimenting with jruby.

**Comment by headius** [comment]
Any luck on getting this further along?

**Comment by deivid-rodriguez** [comment]
No :(

My intention was not to try to fix webrick tests against jruby, only to verify that they were failing.

**Comment by deivid-rodriguez** [comment]
@hsbt Should I get these changes (excluding jruby), so that we can migrate to Github Actions?

**Comment by headius** [comment]
I have filed jruby/jruby#6248 which discusses the `test_cgi` failure. In short it won't be possible to support arbitrary bytes passed via environment variables (as is the case in the quoted test_cgi example) without JRuby bypassing the JDK's own environment variable support.

I believe the test in question should have its exclusion expanded to the "java" platform for now, since there's no timeline for us to reimplement environment variable support in JRuby.

https://github.com/ruby/webrick/blob/bfac1add47dbb64edb119d2d98bc63263040a043/test/webrick/test_cgi.rb#L46

Note also jruby/jruby#6246 which should fix the remaining failures (I'm down to about 4 or 5).

**Comment by deivid-rodriguez** [comment]
@hsbt I updated this PR to limit it to only migrating the current TravisCI configuration to Github Actions. Let me know!

**Comment by hsbt** [comment]
Seems fine. Thanks!

**Pull request merged**
